services:
  - type: web
    name: Jagirdar--bot
    runtime: python-3.11
    buildCommand: |
      apt-get update -y && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python bot.py
